"""Build the two dependency-free bilingual pages: python build_site.py."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parent
GUIDE = 'https://www.kirklandwa.gov/files/sharedassets/public/v/1/parks-amp-comm-services/recreation/rec-guide/2026-fall-2027-winter-recreation-guide_youth.pdf'
RENTAL = 'https://www.kirklandwa.gov/files/sharedassets/public/v/1/parks-amp-comm-services/pdfs/finalized-rental-guide-5.26.26.pdf'
KIT = 'https://thamesandkosmos.com/products/kids-first-coding-robotics-classroom-bundle-10-pack'
PROPOSAL = 'https://www.kirklandwa.gov/files/sharedassets/public/v/1/parks-amp-comm-services/recreation/recreation-program-proposal.pdf'

def bi(zh, en):
    return f'<span lang="zh-Hant">{zh}</span><span lang="en">{en}</span>'

def p(zh, en, cls=''):
    return f'<p class="{cls}">{bi(zh,en)}</p>'

def heading(zh, en, level=2):
    return f'<h{level}>{bi(zh,en)}</h{level}>'

def link(url, zh, en, cls=''):
    return f'<a class="{cls}" href="{escape(url, quote=True)}">{bi(zh,en)}</a>'

def shell(content, planning=False):
    title_zh = '開班與定價試算｜PecuLab 文化邏輯探索課' if planning else '文化邏輯探索課｜PecuLab K–2 課後共學'
    title_en = 'Program & Pricing Planner | PecuLab' if planning else 'Little Thinkers: Stories, Maps & Robots | PecuLab'
    return f'''<!doctype html>
<html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="theme-color" content="#f8f6ef"><meta name="description" content="PecuLab K–2 文化邏輯探索課：每週三 50 分鐘，以故事、地圖與實體機器人練習思考。Screen-free stories, maps and robotics. Kirkland pilot proposal.">
<title>{title_zh}</title><link rel="stylesheet" href="styles.css"></head>
<body data-title-zh="{title_zh}" data-title-en="{title_en}">
<a class="skip" href="#main">{bi('跳至內容','Skip to content')}</a>
<header><div class="container header-inner"><a class="brand" href="index.html"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i><i></i></span>PECULAB <span style="font-weight:400;letter-spacing:0;font-size:12px">little thinkers</span></a>
<nav aria-label="Main navigation">{link('index.html#curriculum','全年課程','The learning year','nav-link')}{link('index.html#pilot','試辦資訊','The pilot','nav-link')}{link('planning.html','開班規劃','Planning','nav-extra')}
<div class="lang-switch" role="group" aria-label="Language / 語言"><button type="button" data-language="zh-Hant" aria-pressed="true">中文</button><button type="button" data-language="en" aria-pressed="false">EN</button></div></nav></div></header>
<main id="main">{content}</main>
<footer><div class="container footer-inner"><div>© 2026 PecuLab LLC · Kirkland, Washington<br>{bi('課程提案 · 場地、日期與費用待確認','Program proposal · Venue, dates and fees pending confirmation')}</div><div>{link('index.html','課程介紹','Course overview')} · {link('planning.html','定價與開班試算','Pricing & class planner')} · {link('../index.html','PecuLab 首頁','PecuLab home')}</div></div></footer>
<noscript><div class="container nojs">本頁中文內容可直接閱讀；中英文切換與試算需要 JavaScript。Enable JavaScript for English and the interactive calculator.</div></noscript><script src="app.js"></script></body></html>'''

# Original learning sequence; not a reproduction of the kit's 30-lesson manual.
# Each week lists a mission and observable evidence of learning.
modules = [
 ('01', '秋季上 · 試辦 6 堂', 'Early fall · 6-session pilot', '故事裡的第一條路', 'A story, a robot, a first route',
  '從「先做什麼」開始，練習方向、順序、輪流與除錯。', 'Start with what comes first: direction, sequencing, turn-taking and debugging.', [
  ('我的機器人朋友','Meet my robot friend','以身體扮演機器人，排出 3 張動作卡；能分辨想法與明確指令。','Act as a robot and arrange three action cards; distinguish an idea from a precise instruction.'),
  ('幫角色找到家','Help a character get home','在地圖排出 3–5 個步驟，執行前先指出預期終點。','Plan a 3–5-step route and point to the predicted destination before running it.'),
  ('我的社區小地圖','Map my neighborhood','畫出家、圖書館與公園；說出一段包含轉彎的路線。','Draw a home, library and park; explain a route that includes a turn.'),
  ('故事便當送到了','Deliver a story lunch','用紙製食物圖卡設計兩站配送；能把任務分成兩小段。','Use paper food pictures for a two-stop delivery; split the task into two smaller parts.'),
  ('走錯了，再試一次','A wrong turn, another try','找出教師預設的一張錯卡，只改一個地方再測試。','Find one deliberately misplaced card; change one thing and test again.'),
  ('我的第一場小分享','My first mini showcase','和夥伴展示原創路線，說出「我改了什麼、為什麼」。','Present an original route with a partner and explain one change and its reason.')]),
 ('02','秋季下 · 6 堂','Late fall · 6 sessions','節慶與重複的節奏','Celebrations & repeating patterns',
  '把重複的動作找出來，讓迴圈變成摸得到的節奏。','Find repeated actions and make loops tangible through rhythm.',[
  ('圖案接龍','Pattern parade','以顏色與拍手找出 AB／AAB 規律；預測下一個動作。','Use colors and claps to find AB/AAB patterns and predict the next action.'),
  ('機器人跳舞','Robot dance','先排重複的動作，再以簡單迴圈取代；執行並比較。','Build repeated actions, replace them with a simple loop, then compare the runs.'),
  ('燈光小路','A path of lights','用紙燈籠地圖重複移動與停頓；指出迴圈的範圍。','Repeat moves and pauses on a paper lantern map; identify the loop body.'),
  ('冬日郵差','Winter mail carrier','將相同的送信動作重複 2–3 次；每次輪換操作角色。','Repeat a delivery action two or three times, switching partner roles each run.'),
  ('找出多走的一步','One step too many','比較重複次數不同的兩個程式；修正過頭的路徑。','Compare two repeat counts and fix a route that overshoots.'),
  ('我們的節慶遊行','Our celebration parade','自選家庭或想像中的慶祝方式，展示一個有迴圈的路線。','Choose a family or imaginary celebration and demonstrate a route with a loop.')]),
 ('03','冬季 · 6 堂','Winter · 6 sessions','地圖裡的小小設計師','Designers of small worlds',
  '練習拆解任務、規劃多站路線，尊重每個人的故事。','Break tasks apart, plan multiple stops and make room for different stories.',[
  ('出發前的計畫','Plan before we go','畫出起點、目的地與障礙；用手指預演後再排卡。','Draw a start, goal and obstacle; trace the plan before coding.'),
  ('市場採買任務','A market mission','選擇三張物品圖卡，把採買路線拆成三段。','Choose three item cards and divide a shopping route into three parts.'),
  ('拜訪朋友','Visit a friend','比較兩條都能抵達的路，說出自己的選擇理由。','Compare two successful routes and explain a preference.'),
  ('我的家庭小傳統','A tradition from home','以自選的家庭活動編排故事順序，讓機器人演出其中一段。','Sequence a chosen family activity and let the robot act out one part.'),
  ('任務交接站','Pass the plan','交換地圖與指令，觀察同伴能否依自己的說明完成。','Exchange maps and instructions; observe whether a partner can follow them.'),
  ('社區故事地圖展','Neighborhood map exhibit','完成三站任務，展示規劃圖與修正後的卡片順序。','Complete a three-stop mission and show the plan alongside the revised sequence.')]),
 ('04','春季上 · 6 堂','Early spring · 6 sessions','觀察、測試、一起修正','Observe, test & improve',
  '從看見結果到找出原因，逐步加入簡單規則。','Move from observing results to finding causes, with simple rules along the way.',[
  ('小小測試員','Little testers','在紀錄卡上畫出預測與實際結果；找出第一個不同。','Draw predicted and actual results; identify the first difference.'),
  ('公園裡的岔路','A fork in the park','用角色扮演練習「如果有障礙，就改道」；口述規則。','Role-play “if the path is blocked, take another route” and explain the rule.'),
  ('看見訊號再出發','A signal to start','以紙製訊號練習等待與觸發；區分先後與開始條件。','Use paper signals to practice waiting and triggering; distinguish sequence from a start condition.'),
  ('一次改一個地方','Change one thing','針對失敗路徑提出猜想，只改一張卡並記下結果。','Suggest a reason for failure, change one card and record the result.'),
  ('我說，你來測','You test my idea','夥伴測試彼此的方案，用「我觀察到」描述結果。','Test a partner’s plan and describe the outcome using “I noticed…”.'),
  ('春日救援任務','Spring rescue mission','完成繞過障礙的任務，展示至少一次測試與修正。','Complete an obstacle detour and show at least one test and revision.')]),
 ('05','春季下 · 6 堂','Late spring · 6 sessions','把想法變成作品','An idea becomes a project',
  '以可重用的步驟與數量表徵，完成自己的文化故事。','Use reusable steps and number representations in an original cultural story.',[
  ('給動作取名字','Name an action','為一小段常用步驟命名，先用紙卡重用同一段指令。','Name a short routine and reuse it with paper cards.'),
  ('機器人的計數袋','A robot’s counting bag','用代幣記錄已送達的物品數，說出數字代表什麼。','Use tokens to track deliveries and explain what the number represents.'),
  ('我的故事提案','Pitch my story','畫出角色、目標與三段情節；提出一個能測試的成功條件。','Draw a character, goal and three story parts; define a testable success condition.'),
  ('搭建與第一次測試','Build & test once','用教具與紙製場景搭建，保留初版程式的紀錄。','Build with the kit and paper scenery; record the first program version.'),
  ('讓作品更清楚','Make the story clearer','依同伴回饋改進路線或說明，指出修改前後的差異。','Use peer feedback to improve a route or explanation and show what changed.'),
  ('小小故事發表會','Little storytellers’ showcase','向家長或同班夥伴示範，說明目標、測試與一次修正。','Demonstrate to families or classmates and explain the goal, tests and one revision.')]),
 ('06','暑期延伸 · 6 堂','Summer · 6 optional sessions','帶著好奇心去旅行','Travel with curiosity',
  '用新的故事重訪核心能力，暑期仍維持每週 50 分鐘。','Revisit core skills through new stories, still meeting for 50 minutes each week.',[
  ('行李整理演算法','Pack with a plan','排列出遊準備步驟，交換後檢查有沒有遺漏。','Sequence trip preparations and check a partner’s plan for missing steps.'),
  ('城市探險家','City explorer','選擇真實或想像城市，在新地圖規劃一條路。','Choose a real or imagined city and plan a route on a new map.'),
  ('跨海小郵差','Mail across the sea','把長途故事分段，使用重複步驟完成配送。','Split a long-distance story into parts and reuse steps for delivery.'),
  ('朋友設計的迷宮','A friend’s maze','先預測、再測試同伴設計的迷宮；提出一項改善。','Predict and test a partner-designed maze, then suggest an improvement.'),
  ('一起創造新世界','Build a world together','共同訂定目標並分工，每個孩子負責一段程式與一次測試。','Agree on a goal and share roles; each child contributes a sequence and a test.'),
  ('我的思考旅行冊','My thinking journal','比較早期與現在的作品，說出自己學會的一種解題方法。','Compare early and recent work and describe one problem-solving strategy learned.')])
]

def curriculum():
    html = '<div class="curriculum">'
    week = 0
    for number, period_zh, period_en, name_zh, name_en, desc_zh, desc_en, lessons in modules:
        html += f'<details class="module"><summary><div class="module-head"><span class="tag">{bi(period_zh,period_en)}</span><span class="expand" aria-hidden="true">+</span></div>{heading(number+" / "+name_zh,number+" / "+name_en,3)}{p(desc_zh,desc_en,"module-desc")}</summary><ol class="lesson-list">'
        for zh,en,out_zh,out_en in lessons:
            week += 1
            html += f'<li><span class="week">{week:02}</span><div><strong>{bi(zh,en)}</strong>{p(out_zh,out_en)}</div></li>'
        html += '</ol></details>'
    return html + '</div>'

art = '<figure class="kit-hero"><div class="board-top"><span>MEET SAMMY</span><span>KIDS FIRST</span></div><img src="assets/sammy-robot.jpg" width="1000" height="1000" fetchpriority="high" alt="Sammy 機器人 / Sammy robot from Kids First Coding &amp; Robotics"><figcaption><strong>Kids First Coding &amp; Robotics</strong>'+p('孩子的第一位程式小夥伴。','A first coding companion for little thinkers.')+link(KIT,'教材照片來源：Thames &amp; Kosmos ↗','Product photo: Thames &amp; Kosmos ↗','small')+'</figcaption></figure>'

materials = '<section class="section materials-section" id="materials"><div class="container"><div class="section-top"><div>'+p('OUR CLASSROOM KIT','OUR CLASSROOM KIT','eyebrow')+heading('摸得到的程式，<br>看得見的想法。','Code they can touch.<br>Ideas they can see.')+'</div>'+p('課堂使用 Kids First Coding &amp; Robotics。孩子以實體指令卡安排步驟，搭配地圖與積木模型，讓機器人執行自己的計畫。','Our classroom kit is Kids First Coding &amp; Robotics. Children arrange physical command cards and use maps and building pieces to bring their plans to life.')+'</div><div class="kit-gallery"><figure><a href="assets/classroom-bundle.jpg"><img src="assets/classroom-bundle.jpg" width="1000" height="1000" loading="lazy" decoding="async" alt="Kids First Coding &amp; Robotics 十套教室組包裝 / Classroom Bundle 10-Pack packaging"></a><figcaption>'+heading('10 套教室組','Classroom Bundle 10-Pack',3)+p('每位學生自備一套，教材歸學生所有並於每次上課攜帶。可自行購買；班上湊滿 10 位需要購買教材的同學，即可協調 10 套組團購。','Each student owns and brings one complete kit to every class. Families may purchase independently, or coordinate a ten-pack group order when ten classmates need a kit.')+'</figcaption></figure><figure><a href="assets/classroom-contents.jpg"><img src="assets/classroom-contents.jpg" width="1200" height="1200" loading="lazy" decoding="async" alt="積木、齒輪、地圖與實體指令卡 / Building pieces, gears, map tiles and physical command cards"></a><figcaption>'+heading('積木 × 地圖 × 指令卡','Building pieces, maps &amp; code cards',3)+p('先排出想法，再讓機器人試走。從順序、轉彎與重複開始，練習觀察、修正與分享。','Arrange an idea, then let the robot try it. Begin with sequences, turns and repetition, practicing observation, revision and sharing.')+'</figcaption></figure></div>'+p('產品照片來源：Thames &amp; Kosmos 官方產品頁。點選照片可查看大圖。','Product photos: the official Thames &amp; Kosmos product page. Select a photo to view it at full size.','small')+link(KIT,'查看官方教材介紹 ↗','Explore the official classroom kit ↗','inline-link')+'</div></section>'

overview = '<div class="container"><section class="hero"><div>'
overview += f'<div class="pill"><span class="dot"></span>{bi("K–2 社區課後共學 · 試辦提案","K–2 community enrichment · Pilot proposal")}</div>'
overview += heading('小小的步驟，<br>讓<em>想法動起來。</em>','Little steps.<br><em>Big discoveries.</em>',1)
overview += p('文化邏輯探索課','Stories, Maps & Robots','eyebrow')
overview += p('一個故事、一張地圖、一個機器人。孩子和夥伴一起排出步驟、試試看、改一改，把腦中的想像變成看得見的行動。','A story, a map and a little robot. Children plan a path with a partner, try it, make a change and watch their ideas come to life.','lead')
overview += '<div class="actions">'+link('#pilot','看看 6 週試辦 →','Explore the 6-week pilot →','button')+link('#curriculum','探索一年的學習','Explore the learning year','button secondary')+'</div>'
overview += p('預計於 North Kirkland Community Center 開課；日期與場地尚待確認。','Proposed at North Kirkland Community Center. Dates and venue arrangements are not yet confirmed.','small')+'</div>'+art+'</section><div class="facts">'
for strong_zh,strong_en,sub_zh,sub_en in [('K–2','K–2','幼兒園至二年級 · 約 5–8 歲','Kindergarten–Grade 2 · Approx. ages 5–8'),('每週三','Wednesdays','下午時段 · 確切時間待公告','Afternoons · Exact time to be announced'),('50 分鐘','50 minutes','故事、動手做、測試與分享','Stories, building, testing & sharing'),('目標 10 人','10 learners','小班試辦 · 每人自備一套教材','Pilot target · Each learner brings a kit')]:
    overview += f'<div class="fact"><strong>{bi(strong_zh,strong_en)}</strong><span>{bi(sub_zh,sub_en)}</span></div>'
overview += '</div></div><section class="section"><div class="container"><div class="section-top"><div>'+p('A LITTLE SPACE TO THINK','A LITTLE SPACE TO THINK','eyebrow')+heading('給孩子一段，<br>親手思考的時間。','Room to wonder.<br>Time to think.')+'</div>'+p('從孩子自己的故事出發，練習在 AI 時代同樣重要的能力：組織想法、理解結果、和別人一起解決問題。','Start with a child’s own story and practice skills that matter in an AI-filled world: organizing ideas, understanding outcomes and solving problems together.')+'</div><div class="three">'
for n,zh,en,dz,de in [('01','想清楚，再出發','Make a plan','把「我想要」拆成一小步、一小步。以圖像卡與實體地圖學習，不需要閱讀程式碼。','Turn “I want to…” into small, clear steps. Use picture cards and physical maps, with no written code to read.'),('02','試錯，也是一種發現','Learn from a wrong turn','預測機器人會走到哪裡，再觀察結果。走錯了，就找出原因，改一張卡再試。','Predict where the robot will go, then observe. If it takes a wrong turn, find a reason, change a card and try again.'),('03','我的故事，你也能懂','Share a story','從家庭、社區與文化故事取材，練習輪流、聆聽，說出「我為什麼這樣設計」。','Bring family, neighborhood and cultural stories into play. Take turns, listen and explain a design choice.')]:
    overview += f'<article class="feature"><span class="num">{n} /</span>{heading(zh,en,3)}{p(dz,de)}</article>'
overview += '</div></div></section><section class="section green-section"><div class="container">'+p('50 MINUTES, ONE SMALL ADVENTURE','50 MINUTES, ONE SMALL ADVENTURE','eyebrow')+heading('一堂課，剛剛好的探索。','One class. A whole little adventure.')+p('每個孩子操作自己的教材，也和夥伴交換想法、互相觀察測試結果。','Each child works with their own kit and exchanges ideas and test observations with a partner.','muted')+'<div class="rhythm">'
for time,zh,en,dz,de in [('5′','故事開場','A story begins','認識今天的角色與任務。','Meet a character and a challenge.'),('8′','身體想一想','Think with movement','走一走、排圖卡、做預測。','Move, arrange pictures and predict.'),('22′','動手做與測試','Build & test','各自排卡與執行，和夥伴交流。','Code and test with individual kits; compare ideas with a partner.'),('10′','修改與分享','Revise & share','改一個地方，說明發現。','Change one thing and explain the discovery.'),('5′','收拾與回顧','Reset & reflect','零件歸位，帶走一個好問題。','Sort the pieces and take a good question home.')]:
    overview += f'<article><strong>{time}</strong>{heading(zh,en,3)}{p(dz,de)}</article>'
overview += '</div></div></section><section class="section" id="curriculum"><div class="container"><div class="section-top"><div>'+p('THE LEARNING YEAR','THE LEARNING YEAR','eyebrow')+heading('六個篇章，<br>陪想法慢慢長大。','Six chapters.<br>A year of growing ideas.')+'</div>'+p('全年 36 堂：學年 30 堂＋暑期延伸 6 堂。每梯次 6 堂，先從第一梯試辦開始，再依孩子的投入與學習情況續開。','36 sessions across the year: 30 during the school year plus 6 optional summer sessions. Enroll by six-session block, beginning with the pilot.')+'</div>'+curriculum()
overview += p('季節為完整年度配置範例；若試辦較晚開始，全部順延，不是已核定行事曆。第一梯的 6 堂已包含在 36 堂內；每週三一次，假期與場館休館日不排課。正式日期將依學校行事曆、場地與家庭接送時間排定。暑期另行報名，非全天營隊。','Seasons illustrate a full-year sequence, not a confirmed calendar. A later pilot start shifts the sequence forward. The six pilot sessions are included in the 36-session total. Classes meet once each Wednesday, with breaks for holidays and facility closures. Dates will be set around school calendars, room availability and family travel time. Summer is a separate weekly course, not a day camp.','note')
overview += '<div class="three block-heading">'
for zh,en,dz,de in [('K：從看圖與操作開始','Kindergarten: see & try','用 3–5 張卡、短路徑、手指預演與口語說明；協助孩子準備自己的底座，讓時間留給思考。','Use 3–5 cards, short routes, finger tracing and oral explanations. Help each child prepare their own robot base.'),('1–2 年級：多想一步','Grades 1–2: add a challenge','增加多站路線、簡單迴圈與設計紀錄。熟悉核心任務後，再選擇條件、函式或數量的延伸。','Add multiple stops, simple loops and design notes. Offer conditions, routines and number extensions after core tasks are secure.'),('每 6 堂，看得見成長','Notice growth every six weeks','保留一張路線圖、一份卡片紀錄與孩子的一句解釋；觀察規劃、測試、修正、合作與表達。','Keep a route map, a card sequence and a child’s explanation. Observe planning, testing, revising, teamwork and communication.')]:
    overview += '<article class="feature">'+heading(zh,en,3)+p(dz,de)+'</article>'
overview += '</div>'+p('課程使用 Kids First Coding & Robotics 為教材規劃基礎，加入 PecuLab 原創故事與文化任務；不是逐堂照搬原廠教案。條件與函式先以角色扮演、紙卡理解，再依教具版本與準備度延伸；不要求所有 K–2 學生掌握進階語法。','The plan uses Kids First Coding & Robotics with original PecuLab stories and cultural tasks; it does not reproduce the manufacturer’s lesson sequence. Conditions and routines begin with role-play and paper cards, with kit extensions matched to the version and learner readiness. Advanced syntax is not a requirement.','small')+'</div></section>'
overview += '<section class="section" id="pilot" style="background:#eeeee4"><div class="container split"><div>'+p('START SMALL, LEARN TOGETHER','START SMALL, LEARN TOGETHER','eyebrow')+heading('先用六次相遇，<br>開始第一段旅程。','Begin with six<br>small adventures.')+p('第一梯聚焦順序、方向、合作與除錯。孩子不需要有機器人或程式經驗，也不需要一次承諾一整年。','The first block focuses on sequencing, direction, collaboration and debugging. No robotics or coding experience is needed, and families do not need to commit to a full year.','lead')+'<ul class="checklist">'
for zh,en in [('建議 8 人起班，目標 10 人；以實際合作成本確認最低人數。','Suggested minimum 8, target 10; final minimum depends on agreed costs.'),('規劃 1 位主教＋1 位助教，每位學生自備一套教材。','Plan for one lead instructor and one assistant; each learner brings their own kit.'),('建議學費含教學與課堂基本耗材，不含教材購置費；教材可帶回家繼續探索。','Proposed tuition covers instruction and basic class supplies, not the kit purchase. Students take their kits home to keep exploring.'),('網站提供中英文資訊；授課語言與中文支援方式將於開班前確認。','Course information is bilingual; teaching language and Mandarin support will be confirmed before enrollment.')]:
    overview += '<li>'+bi(zh,en)+'</li>'
overview += '</ul></div><div class="price-card">'+p('建議試辦費用 · 美元','PROPOSED PILOT TUITION · USD','eyebrow')+'<div class="price">$180 <small>'+bi('／6 堂','/ 6 sessions')+'</small></div>'+p('每堂 50 分鐘 · 每堂 US$30 · 教材另購','50 minutes per session · US$30 per session · Kit purchased separately')+p('此為與社區中心洽談用的建議價，尚未開放付款或正式報名。若由市府辦理，居民／非居民價與任何適用稅費將依最終核定內容公告。','This is a proposed price for discussion with the community center. Payment and enrollment are not open. If city-operated, resident/nonresident rates and any applicable taxes will be published after approval.')+link('#contact','了解試辦進度 →','Pilot details & inquiries →','button')+p('6 堂為一梯；後續梯次依試辦結果調整。','Six sessions per block; later blocks may change based on pilot feedback.','small')+'</div></div></section>'
overview += '<section class="section"><div class="container split"><div>'+p('GOOD QUESTIONS','GOOD QUESTIONS','eyebrow')+heading('家長可能想知道的事。','A few things families may wonder.')+'</div><div class="faq">'
for zh,en,dz,de in [('孩子需要帶平板或電腦嗎？','Does my child need a screen?','不需要。主要使用實體指令卡、地圖、機器人與紙筆，讓孩子親手安排與觀察。','No. Children primarily use physical command cards, maps, robots, paper and pencils.'),('這是 AI 操作課嗎？','Is this an AI tools class?','課程著重思考的基礎：先預測、再測試，辨認錯誤並說明自己的選擇。不需要孩子使用生成式 AI 帳號。','The focus is foundational thinking: predict, test, identify an error and explain a choice. Children do not need generative AI accounts.'),('文化主題需要特定背景嗎？','Do families need a particular cultural background?','不需要。孩子可分享自己的家庭故事，也可選擇想像情境；不以單一節慶或文化經驗作為先備條件。','No. Children may share a family story or choose an imaginary setting. No particular cultural or holiday knowledge is assumed.'),('有接送或延長照顧嗎？','Is transport or extended care included?','目前規劃為單次 50 分鐘課程，家庭自行接送。確切報到、接回時間與照顧安排會在正式招生時公告。','The plan is a 50-minute enrichment class with family-arranged transport. Check-in, pickup and care arrangements will be published with enrollment details.'),('缺課、取消或停課怎麼辦？','What happens if a class is missed or canceled?','正式報名前會公告最低開班人數、退費、缺課與補課規則。若由市府承辦，將明確連結適用的市府規定。','Minimum enrollment, withdrawal, missed-class and makeup terms will be published before registration. City-run enrollment will link to the applicable city policy.')]:
    overview += '<details><summary>'+bi(zh,en)+'</summary>'+p(dz,de)+'</details>'
overview += '</div></div></section><section class="section" id="contact"><div class="container contact"><div>'+p('MEET IN THE NEIGHBORHOOD','MEET IN THE NEIGHBORHOOD','eyebrow')+heading('在社區裡，<br>一起把第一班做起來。','A small learning community,<br>close to home.')+p('目前為規劃中的試辦。歡迎透過 PecuLab 詢問課程；確定合作方式、場地與日期後，才會公布正式報名連結。','This pilot is in planning. Contact PecuLab about the course; an enrollment link will be published after the venue, partnership and dates are confirmed.')+'<div class="actions">'+link('https://www.facebook.com/PecuLabLLC','前往 PecuLab 詢問','Contact PecuLab on Facebook','button')+'</div></div><div><address><strong>North Kirkland Community Center</strong><br>12421 103rd Avenue NE<br>Kirkland, WA 98034</address>'+p('預計上課地點 · 尚未完成場地確認','Proposed location · Venue not yet confirmed','small')+link('https://www.google.com/maps/search/?api=1&query=North+Kirkland+Community+Center','查看地圖 ↗','View map ↗','inline-link')+p('本頁為 PecuLab 課程提案，非市府已核定課程公告。','This is a PecuLab proposal, not an approved City of Kirkland course listing.','small')+'</div></div></section>'

planner = '<div class="container"><div class="planner-hero">'+p('PROGRAM DESIGN / WORKING BUDGET','PROGRAM DESIGN / WORKING BUDGET','eyebrow')+heading('一班幾個人，<br>才能好好教，也做得下去？','A class that works<br>for learners and teachers.',1)+p('建議先以 10 人、1 位主教＋1 位助教、6 堂 US$180 提案。每人自購教材，學費與教材費分開。下列假設的財務損益兩平為 7 人；建議仍以 8 人起班、10 人為招生目標。','Propose 10 learners, one lead plus one assistant, and US$180 for six sessions. Students purchase their own kits separately from tuition. Financial break-even is seven under this model; retain a suggested eight-learner minimum and a target of ten.','lead')+p('研究日期：2026-09-22 · 所有金額均為美元 · 合約與成本尚待確認','Researched 2026-09-22 · All amounts in USD · Costs and contract remain unconfirmed','small')+'</div>'
planner += '<div class="three">'
for zh,en,dz,de in [('10 人最適合先試','Start with 10','十位學生各自帶一套教材，可兩人討論、各自操作。主教負責全班引導，助教協助操作與轉場；湊滿十位購買需求可協調團購。','Ten students each bring a kit, discussing in pairs while working individually. The lead guides the group; the assistant supports hands-on work and transitions. Ten kit buyers can coordinate a group order.'),('8 人起班，10 人較穩健','Eight to start, ten preferred','以 US$30／堂、30% 分潤與本頁成本估算，8 人每堂餘額 US$24，10 人 US$60；學生教材費不計入課程營收或成本。','At US$30 per session, a 30% city share and the modeled costs, eight learners leave US$24 per class; ten leave US$60. Student kit purchases are outside course revenue and costs.'),('先談合作開課','Discuss a city partnership','公開多功能室租價不利單班試辦。優先洽談課程承包／分潤與可用教室；不能預設已有優惠。','The public multipurpose-room rental is costly for a single pilot. Discuss a course contract, revenue share and a suitable classroom; discounted space is not assumed.')]:
    planner += '<article class="feature">'+heading(zh,en,3)+p(dz,de)+'</article>'
planner += '</div><section class="section" id="benchmarks">'+p('01 / LOCAL PRICE REFERENCES','01 / LOCAL PRICE REFERENCES','eyebrow')+heading('用同齡、同地點的課程作比較。','Compare age, location and teaching time.')+p('已讀取市府最新 2026 秋／2027 冬 Youth 手冊。REC1 即時目錄回傳 403，因此以下為官方手冊刊載費率，不宣稱是即時剩餘名額或最終結帳價。','The current Fall 2026 / Winter 2027 city Youth guide was reviewed. The REC1 live catalog returned 403, so these are published guide prices, not live availability or final checkout quotes.')
planner += '<div class="table-wrap"><table><thead><tr>'+''.join('<th>'+bi(z,e)+'</th>' for z,e in [('官方課程／編號','Official course / ID'),('年齡與課程量','Age & instruction'),('居民／非居民','Resident / nonresident'),('居民價換算','Resident comparison')])+'</tr></thead><tbody>'
benchmarks = [
 ('Little Coders: Intro to Coding · 25079','NKCC · Coding with Kids · 2026/9/21–11/9','5–7 歲 · 8 × 60 分鐘','Ages 5–7 · 8 × 60 min','$234 / $281','$29.25／堂；$24.38／50 分鐘','$29.25/session; $24.38/50 min'),
 ('Wilderness Medicine · 24865','NKCC · Little Medical School · 2026/9/17–11/19','7–11 歲 · 10 × 60 分鐘','Ages 7–11 · 10 × 60 min','$380 / $456','$38／堂；$31.67／50 分鐘','$38/session; $31.67/50 min'),
 ('Elementary Tumbling 1 · 24971','NKCC · 2026/9/16–10/21','5–7 歲 · 6 × 45 分鐘','Ages 5–7 · 6 × 45 min','$72 / $86','$12／堂；$13.33／50 分鐘','$12/session; $13.33/50 min')]
for name,sub,az,ae,fee,nz,ne in benchmarks:
    planner += f'<tr><td><a href="{GUIDE}">{name}</a><small>{sub}</small></td><td>{bi(az,ae)}</td><td>{fee}</td><td>{bi(nz,ne)}</td></tr>'
planner += '</tbody></table></div>'+p('課次依日期區間與手冊列示停課日計算；來源：Youth 手冊印刷頁 22、23、25。換算公式＝總學費 ÷ 課次 ÷ 每堂分鐘 × 50。時長換算只用來比較，不代表不同學科的價值相同，也未推定教材費是否另收。','Session counts are derived from listed date ranges and exclusions (printed pages 22, 23 and 25). Normalization: tuition ÷ sessions ÷ minutes × 50. It is a time comparison, not an assertion that subjects have equal value; unlisted material fees are not inferred.','small')
planner += p('定價判斷：US$180／6 堂＝US$30／50 分鐘，約比同齡 Little Coders 的時間換算價高 23%。這個定位需要小班、個別操作指導、助教與具體學習紀錄來支撐；不是最低價方案。可測試 US$168–180，US$168 在 8 人時每堂約剩 US$12.80；仍建議以 10 人招生。學費不含教材，需同時評估家庭首梯的總負擔。若市府沿用約 20% 非居民加價，US$216 僅是提案試算，不能當作已核定費率。','Pricing judgment: US$180/6 = US$30/50 minutes, about 23% above Little Coders after time normalization. Small groups, individual guidance, an assistant and visible learning records must support this position. A US$168–180 range can be tested, US$168 leaves about US$12.80 per class at eight learners under this model. Target ten learners and consider the separate kit purchase in a family’s first-block budget. If the city applies an approximately 20% nonresident premium, US$216 is an illustration only, not an approved fee.','note')+'</section>'
planner += '<section class="section" style="padding-top:0">'+p('02 / VENUE MAKES THE DIFFERENCE','02 / VENUE MAKES THE DIFFERENCE','eyebrow')+heading('同樣 10 人，合作與租場差很多。','Same ten learners. Very different venue costs.')+'<div class="split"><div>'+heading('方案 A：課程合作／分潤','A / City course partnership',3)+p('試算先假設市府收取學費 30%，包含場地與報名服務，不再另加公開場租。這是規劃假設，尚未查到本課程可適用的實際比例。','The model assumes a 30% city share covering the room and registration, with no additional public room rental. This is a planning assumption; no applicable contract percentage has been confirmed.')+p('10 人：每堂收入 $300 − 分潤 $90 − 變動成本 $30 − 固定成本 $120＝餘額 $60；6 堂 $360。','Ten learners: $300 revenue − $90 city share − $30 variable costs − $120 fixed costs = $60 per session, or $360 over six sessions.')+'</div><div>'+heading('方案 B：按公開價自行租場','B / Rent at published public rates',3)+p('2026-05-26 租借指南第 4 頁：NKCC 多功能室居民 $125／小時、非居民 $150／小時；週一至四至少租 2 小時。因此每週最低場租為 $250／$300，不是只付 50 分鐘。第 6 頁另列 $300 可退押金。','The May 26, 2026 rental guide, page 4, lists NKCC’s multipurpose room at $125/hour resident or $150/hour nonresident, with a two-hour Monday–Thursday minimum. Minimum weekly rent is therefore $250/$300, not 50 minutes. Page 6 also lists a $300 refundable deposit.')+p('採居民場租與 3% 金流假設，10 人每堂約虧 $109；需 15 人才損益兩平，已超過試辦建議規模。應另談合作教室與費率，不以擴班解決。','With resident rent and an assumed 3% payment fee, ten learners lose about $109 per session; break-even is 15 learners, above the pilot’s recommended size. Negotiate an appropriate room and arrangement instead of enlarging the class.')+link(RENTAL,'查看官方租借指南 ↗','Read the official rental guide ↗','inline-link')+'</div></div></section>'
planner += '<section class="section" style="padding-top:0" id="calculator">'+p('03 / TRY YOUR NUMBERS','03 / TRY YOUR NUMBERS','eyebrow')+heading('把成本填進來，看看一班的餘額。','Put the assumptions to work.')+p('教師費包含實際投入的備課、上課與收拾時間。預設主教 $80＝2 小時 × $40；助教 $30＝1 小時 × $30；行政與雜支 $10；學生教材自購，不列為課程方設備成本；教師專用設備預算預設 $0（假設已有，若需新購請填入）；耗材每生每堂 $3。全部是可修改的預算值，不是場館或教師報價。','Staff pay includes the time actually worked. Defaults: lead $80 = 2 hours × $40; assistant $30 = 1 hour × $30; overhead $10; student-owned kits are excluded; instructor-only equipment defaults to $0, assuming it is already available (enter any new purchases); consumables $3 per learner per session. All are editable budget assumptions, not quotes.')+'<div class="calculator"><form id="cost-form" class="controls"><label class="full">'+bi('營運方式','Operating model')+'<select id="mode"><option value="city">A · City partnership / 市府合作</option><option value="rental">B · Public room rental / 公開租場</option></select></label>'

def field(id,zh,en,value,min=0,max=100000,step='0.01',mode=None):
    attr = f' data-mode="{mode}"'+(' hidden' if mode=='rental' else '') if mode else ''
    return f'<label{attr}>{bi(zh,en)}<input id="{id}" type="number" min="{min}" max="{max}" step="{step}" value="{value}" required></label>'

for args in [
 ('students','學生人數','Learners',10,1,30,'1',None),('fee','每生每梯學費 $','Tuition / learner / block $',180,1,10000,'0.01',None),('weeks','每梯堂數','Sessions / block',6,1,52,'1',None),('share','市府分潤 %（假設）','City share % (assumed)',30,0,100,'0.1','city'),('rent','場租 $／小時','Room $ / hour',125,0,10000,'0.01','rental'),('hours','每次租用小時（至少 2）','Booked hours (minimum 2)',2,2,12,'0.5','rental'),('processing','金流費 %（假設）','Payment fee % (assumed)',3,0,100,'0.1','rental'),('teacher','主教報酬 $／堂','Lead pay $ / session',80,0,10000,'0.01',None),('assistant','助教報酬 $／堂','Assistant pay $ / session',30,0,10000,'0.01',None),('overhead','行政等固定成本 $／堂','Other fixed costs $ / session',10,0,10000,'0.01',None),('variable','耗材 $／生／堂','Supplies $ / learner / session',3,0,1000,'0.01',None),('equipment','教師專用設備預算 $','Instructor-only equipment budget $',0,0,100000,'0.01',None),('life','設備攤提使用次數','Equipment allocation: uses',50,1,1000,'1',None)]:
    planner += field(*args)
planner += '<div class="full"><button type="reset" class="button secondary">'+bi('重設假設','Reset assumptions')+'</button></div></form><div class="result" aria-live="polite" aria-atomic="true"><div id="invalid-input" hidden>'+bi('請填入範圍內的有效數值，才能計算。','Enter valid numbers within the specified ranges.')+'</div><div id="result-content">'+p('每堂營運餘額（扣除師資與設備攤提）','Operating balance / session (after staff & equipment)')+'<div class="large" id="profit">$60.00</div><p id="status"></p><dl>'
for id,zh,en,default in [('gross','學費收入／堂','Tuition revenue / session','$300.00'),('deduction','市府分潤／堂','City share / session','$90.00'),('variableTotal','耗材成本／堂','Supplies / session','$30.00'),('fixed','固定成本含設備／堂','Fixed costs incl. equipment / session','$120.00'),('termProfit','整梯營運餘額','Operating balance / block','$360.00'),('breakEven','損益兩平人數','Break-even enrollment','7'),('cash','首梯現金餘額（扣除教師設備購置）','First-block cash after instructor equipment purchase','$360.00')]:
    label = f'<dt id="deduction-label">{bi(zh,en)}</dt>' if id=='deduction' else f'<dt>{bi(zh,en)}</dt>'
    planner += f'<div>{label}<dd id="{id}">{default}</dd></div>'
planner += '</dl><p id="model-note"></p>'+p('學生自行購買或團購的教材款不列入此試算。教師專用設備若需新購，現金餘額以整筆購置取代攤提，避免重複扣除。未列入押金、稅款、融資、退款及額外啟動成本；保險、行銷等請納入固定成本。退款或折扣會降低收入。','Independent and group purchases of student kits are excluded from this model. For instructor equipment, the cash view replaces allocation with the full purchase, avoiding double counting. Deposits, taxes, financing, refunds and additional launch costs are excluded. Add insurance and marketing to fixed costs; refunds and discounts reduce revenue.')+'</div></div></div><div class="table-wrap"><table><thead><tr>'+''.join('<th>'+bi(z,e)+'</th>' for z,e in [('人數','Learners'),('每堂營收','Revenue / session'),('每堂餘額','Balance / session'),('整梯餘額','Balance / block')])+'</tr></thead><tbody id="scenario-rows"><tr><td>6</td><td>$180</td><td>−$12</td><td>−$72</td></tr><tr><td>8</td><td>$240</td><td>$24</td><td>$144</td></tr><tr class="highlight"><td>10</td><td>$300</td><td>$60</td><td>$360</td></tr><tr><td>12</td><td>$360</td><td>$96</td><td>$576</td></tr></tbody></table></div>'+p('公式：每堂餘額＝人數 × [每生每堂學費 × (1 − 抽成比例) − 每生耗材] − 固定成本。損益兩平人數向上取整。自租模式以金流費取代市府分潤，並在固定成本加上完整租用時數。','Formula: balance = learners × [per-session tuition × (1 − deduction rate) − per-learner supplies] − fixed costs. Break-even rounds up. Rental mode replaces the city share with payment processing and adds all booked room hours to fixed costs.','small')+'</section>'
planner += '<section class="section" style="padding-top:0">'+p('04 / A PILOT WE CAN LEARN FROM','04 / A PILOT WE CAN LEARN FROM','eyebrow')+heading('招生、設備與一年安排。','Enrollment, equipment and the year ahead.')+'<div class="three">'
for zh,en,dz,de in [('人數與教學配置','Group size & staffing','1 位老師單獨帶班，建議先限 6–8 人；10–12 人安排助教。試辦目標 10 人，上限先設 12 人。這是教學配置建議，不是法定師生比。若多數為 K 或需要較多協助，減少名額並重算成本。','For a solo instructor, start with 6–8 learners; use an assistant for 10–12. Target 10 and cap the pilot at 12. These are teaching recommendations, not statutory ratios. Reduce enrollment and recalculate costs if many learners need more support.'),('學生教材與團購','Student kits & group orders','原廠 10 套組頁面列 US$999.95，查詢時顯示缺貨待補。每位學生自行購買一套，或湊滿 10 位有購買需求的同學協調團購；平均每套約 US$100，另計適用稅運費。教材歸學生所有，不由課程學費支付。實際供貨、收款與分配方式須在下單前確認。','The manufacturer lists the ten-pack at US$999.95 and showed it as backordered when checked. Each learner purchases one kit independently, or ten classmates needing kits can coordinate a ten-pack order: approximately US$100 per kit before applicable tax and shipping. Kits belong to students and are not paid from tuition. Confirm availability, payment and distribution before ordering.'),('全年與續班判斷','Year plan & continuation','6 梯 × 6 堂＝36 堂；以 US$180 固定價計，30 堂學年 $900、暑期 $180、全年 $1,080／生，均不含教材且非承諾售價。試辦後檢查出席、每人操作機會、除錯表達、續報意願與實際工時，再決定是否續開。','Six blocks × six sessions = 36. At a constant proposed US$180/block: school year $900, optional summer $180, full year $1,080 per learner. These are tuition-only planning totals, excluding kits, not committed prices. Review attendance, hands-on turns, debugging explanations, return interest and actual staff time before continuing.')]:
    planner += '<article class="feature">'+heading(zh,en,3)+p(dz,de)+'</article>'
planner += '</div>'+p('以預設分潤模型、每梯均 10 人且全年 36 堂計：營收 $10,800，扣除分潤、師資、耗材與行政後，營運及現金餘額均為 $2,160（教師設備預算為 $0）。每位學生的教材費另由家庭支付，不列為課程營收，也不扣成課程成本。這說明單班較適合作為驗證課程與招生需求的試辦；若期待更高盈餘，應提高實際續班率、改善合作條件或另開班，而非無償吸收備課工時。','With the default partnership model, ten paid learners per block and 36 sessions: revenue is $10,800 and operating and cash balances are both $2,160 after staff, supplies, overhead and city share, with no new instructor equipment budgeted. Families pay for their own kits; those purchases are neither course revenue nor course costs. A single class is mainly a pilot for curriculum and demand. Larger earnings require stronger retention, better terms or another class, with preparation time still paid.','note')+'</section>'
planner += '<section class="section" style="padding-top:0">'+p('05 / NEXT CONVERSATION WITH NKCC','05 / NEXT CONVERSATION WITH NKCC','eyebrow')+heading('帶著具體提案，洽談開班條件。','Bring a concrete proposal to NKCC.')+'<ul class="checklist">'
for zh,en in [('合作方式：能否以市府課程承包方式辦理？分潤基礎、比例、場地、報名與退款成本各由誰負擔？','Partnership: is a contracted city course possible? Confirm revenue-share basis, percentage and responsibility for room, registration and refunds.'),('時段與空間：週三下午 50 分鐘，另留布置、接送與收拾時間；需容納十套個人教材的工作桌與測試空間；如需教師示範／備用套組，另行編列。','Space and timing: 50 minutes on Wednesday afternoons, plus setup, pickup and cleanup; work areas and testing space for ten individual kits; budget separately for any instructor demonstration or spare kits.'),('招生設定：提案 8 人起班、10 人目標、12 人上限；確認居民／非居民定價、適用費用、取消與補課規則。','Enrollment: propose minimum 8, target 10, maximum 12; confirm resident/nonresident rates, applicable fees and cancellation/makeup terms.'),('人員安排：確認實際主教／助教、資格與中心要求；助教若需更多工時，先調整預算。','Staff: confirm the lead, assistant, qualifications and center requirements; increase the budget if the assistant needs more paid time.'),('日期與授課語言：核對學校週三放學及交通時間、假期、中文支援與家長需求後，才公布確切開課日期。','Dates and language: verify Wednesday school dismissal, travel time, breaks, Mandarin support and family needs before publishing start dates.')]:
    planner += '<li>'+bi(zh,en)+'</li>'
planner += '</ul>'+p('場地洽詢：North Kirkland Community Center · 425-587-3350 · <a href="mailto:eParks@kirklandwa.gov">eParks@kirklandwa.gov</a>。此頁未代為聯絡或提交申請。','Venue contact: North Kirkland Community Center · 425-587-3350 · <a href="mailto:eParks@kirklandwa.gov">eParks@kirklandwa.gov</a>. No inquiry or application has been sent.')+link(PROPOSAL,'官方課程提案表（使用前確認最新版本） ↗','City course proposal form (confirm current version) ↗','inline-link')+'</section>'
planner += '<section class="section" style="padding-top:0" id="sources">'+p('SOURCE NOTES','SOURCE NOTES','eyebrow')+heading('資料來源與使用範圍。','Sources & scope.')+'<ol class="sources">'
sources = [
 (GUIDE,'City of Kirkland · Fall 2026 / Winter 2027 Youth Guide','印刷頁 22–25：比較課程、年齡、日期與價格。透過官方手冊頁取得連結並下載解析。','Printed pages 22–25: comparison courses, ages, dates and fees. Linked from the city guide page and downloaded for review.'),
 (RENTAL,'City of Kirkland · Facility Rental Guide · 2026-05-26','第 4、6 頁：NKCC 多功能室費率、最低時數與押金；不等於商業課程合約報價。','Pages 4 and 6: room rates, minimum hours and deposit; not a commercial teaching contract quote.'),
 (KIT,'Thames & Kosmos · Classroom Bundle 10-Pack','US$999.95 與供貨狀態；與 ref 中的產品 PDF 相互參照，實際採購另確認稅運費。','US$999.95 and availability; cross-checked with the supplied product PDF. Confirm tax and shipping when purchasing.'),
 ('https://thamesandkosmos.com/pages/educator-resources','Thames & Kosmos · Educator Resources','參考原廠教材對照與 ref 內課程關聯 PDF，未宣稱本原創課程獲 CSTA 認證。','Manufacturer curriculum correlations and the supplied PDF inform the design; no CSTA certification of this original course is claimed.'),
 ('https://www.facebook.com/PecuLabLLC','PecuLab · 課程理念 / Program philosophy','依使用者提供的 ref/Facebook.pdf：故事、文化任務、不插電邏輯、修正與表達。','Based on the supplied ref/Facebook.pdf: stories, cultural tasks, screen-free logic, revision and explanation.'),
 ('https://secure.rec1.com/WA/city-of-kirkland/catalog','City of Kirkland · REC1 live catalog','即時頁面自動讀取受阻（403）；報名與最新價格仍須回到官方目錄確認。','Automated access was blocked (403); verify live pricing and registration in the official catalog.')]
for url,name,dz,de in sources:
    planner += f'<li><a href="{url}">{name}</a><br>{bi(dz,de)}</li>'
planner += '</ol></section></div>'

videos = '<section class="section" id="demos"><div class="container"><div class="section-top"><div>'+p('SEE IT IN ACTION','SEE IT IN ACTION','eyebrow')+heading('看看機器人，<br>怎麼讓指令動起來。','See the robot<br>bring instructions to life.')+'</div>'+p('從指令卡到地圖，看看這套教材的實際操作。點選播放即可觀看，也可以切換全螢幕。','Watch the kit in action with physical command cards and a map. Select play to watch, or switch to full screen.')+'</div><div class="demo-grid">'
for number, title_zh, title_en, duration in [('01','指令卡操作示範','Command card demonstration','0:07'),('02','地圖行走示範','Robot on the map','1:09')]:
    videos += f'<article class="demo-card"><video controls playsinline preload="metadata" width="1280" height="720" poster="assets/demo-{number}-poster.jpg" aria-labelledby="demo-title-{number}"><source src="ref/coding-robotics-demo-{number}.mp4" type="video/mp4">'+bi('您的瀏覽器不支援內嵌影片，請使用下方連結開啟。','Your browser does not support embedded video. Use the link below to open it.')+f'</video><div class="demo-caption"><div class="module-head"><h3 id="demo-title-{number}">'+bi(title_zh,title_en)+f'</h3><span class="tag">{duration}</span></div>'+link(f'ref/coding-robotics-demo-{number}.mp4','另開影片 ↗','Open video ↗','inline-link')+'</div></article>'
videos += '</div></div></section>'
overview = overview.replace('<section class="section" id="curriculum">', materials + videos + '<section class="section" id="curriculum">')
(ROOT/'index.html').write_text(shell(overview),encoding='utf-8')
(ROOT/'planning.html').write_text(shell(planner,True),encoding='utf-8')
print('Built index.html and planning.html; 36 original lesson plans in both languages.')
