from pathlib import Path
p=Path('build_site.py')
s=p.read_text(encoding='utf-8')
replacements = [
('本課程選用的教材組合。課堂採兩人共用一套、輪流操作；教材留在教室使用。','每位學生自備一套，教材歸學生所有並於每次上課攜帶。可自行購買；班上湊滿 10 位需要購買教材的同學，即可協調 10 套組團購。'),
('The selected classroom bundle. Partners share one kit and take turns; kits stay in the classroom.','Each student owns and brings one complete kit to every class. Families may purchase independently, or coordinate a ten-pack group order when ten classmates need a kit.'),
('小班試辦 · 兩人共用一套教材','小班試辦 · 每人自備一套教材'),('Pilot target · One kit per pair','Pilot target · Each learner brings a kit'),
('操作角色至少交換一次，讓每個孩子都有排卡、測試與說明的機會。','每個孩子操作自己的教材，也和夥伴交換想法、互相觀察測試結果。'),
('Partners switch roles at least once so every child can arrange cards, test and explain.','Each child works with their own kit and exchanges ideas and test observations with a partner.'),
('兩人合作，輪流排卡與執行。','各自排卡與執行，和夥伴交流。'),('Work in pairs; take turns coding and testing.','Code and test with individual kits; compare ideas with a partner.'),
('提供已組裝底座，讓時間留給思考。','協助孩子準備自己的底座，讓時間留給思考。'),
('Start with a prepared robot base.','Help each child prepare their own robot base.'),
('規劃 1 位主教＋1 位助教，兩人共用一套教材並輪流。','規劃 1 位主教＋1 位助教，每位學生自備一套教材。'),
('Plan for one lead instructor and one assistant, with one kit per pair.','Plan for one lead instructor and one assistant; each learner brings their own kit.'),
('課堂教具借用與基本耗材納入建議學費，教具留在教室。','建議學費含教學與課堂基本耗材，不含教材購置費；教材可帶回家繼續探索。'),
('Proposed tuition includes classroom kit use and basic supplies; kits remain in class.','Proposed tuition covers instruction and basic class supplies, not the kit purchase. Students take their kits home to keep exploring.'),
('每堂 50 分鐘 · 每堂 US$30','每堂 50 分鐘 · 每堂 US$30 · 教材另購'),
('50 minutes per session · US$30 per session','50 minutes per session · US$30 per session · Kit purchased separately'),
('8 人是下列分潤假設下的損益兩平人數，不是有充裕餘額的招生目標。','每人自購教材，學費與教材費分開。下列假設的財務損益兩平為 7 人；建議仍以 8 人起班、10 人為招生目標。'),
('Eight learners is the break-even threshold under the assumptions below, not a comfortable enrollment target.','Students purchase their own kits separately from tuition. Financial break-even is seven under this model; retain a suggested eight-learner minimum and a target of ten.'),
('五組搭檔、五套操作教具，再備一套替換。主教負責全班引導，助教協助操作、轉場與輪流。','十位學生各自帶一套教材，可兩人討論、各自操作。主教負責全班引導，助教協助操作與轉場；湊滿十位購買需求可協調團購。'),
('Five pairs and five working kits, plus a spare. The lead guides the group; the assistant supports hands-on work, transitions and turn-taking.','Ten students each bring a kit, discussing in pairs while working individually. The lead guides the group; the assistant supports hands-on work and transitions. Ten kit buyers can coordinate a group order.'),
('8 人可開，但餘額很薄','8 人起班，10 人較穩健'),('Eight is a thin margin','Eight to start, ten preferred'),
('8 人每堂僅剩 US$4，10 人剩 US$40。','8 人每堂餘額 US$24，10 人 US$60；學生教材費不計入課程營收或成本。'),
('eight learners leave US$4 per class; ten leave US$40.','eight learners leave US$24 per class; ten leave US$60. Student kit purchases are outside course revenue and costs.'),
('小班、實體教具、助教與具體學習紀錄','小班、個別操作指導、助教與具體學習紀錄'),
('Small groups, physical kits, an assistant and visible learning records','Small groups, individual guidance, an assistant and visible learning records'),
('但 US$168 在 8 人時會虧損，建議以 10 人招生。','US$168 在 8 人時每堂約剩 US$12.80；仍建議以 10 人招生。學費不含教材，需同時評估家庭首梯的總負擔。'),
('but US$168 loses money at eight learners under this model.','US$168 leaves about US$12.80 per class at eight learners under this model. Target ten learners and consider the separate kit purchase in a family’s first-block budget.'),
('固定成本 $140＝餘額 $40；6 堂 $240。','固定成本 $120＝餘額 $60；6 堂 $360。'),
('$140 fixed costs = $40 per session, or $240 over six sessions.','$120 fixed costs = $60 per session, or $360 over six sessions.'),
('每堂約虧 $129','每堂約虧 $109'),('about $129 per session','about $109 per session'),
('設備 $1,000 分 50 次使用攤提＝每堂 $20；','學生教材自購，不列為課程方設備成本；教師專用設備預算預設 $0（假設已有，若需新購請填入）；'),
('equipment $1,000 allocated across 50 uses = $20 per session;','student-owned kits are excluded; instructor-only equipment defaults to $0, assuming it is already available (enter any new purchases);'),
('設備購置預算 $','教師專用設備預算 $'),('Equipment purchase budget $','Instructor-only equipment budget $'),
("budget $',1000,0,100000","budget $',0,0,100000"),
('id="profit">$40.00','id="profit">$60.00'),
("'$140.00'","'$120.00'"),("'$240.00'","'$360.00'"),("'Break-even enrollment','8'","'Break-even enrollment','7'"),
('首梯現金餘額（購入全部設備後）','首梯現金餘額（扣除教師設備購置）'),
('First-block cash after full equipment purchase','First-block cash after instructor equipment purchase'),("'-$640.00'","'$360.00'"),
('現金餘額以整筆設備購置取代設備攤提，避免重複扣除。','學生自行購買或團購的教材款不列入此試算。教師專用設備若需新購，現金餘額以整筆購置取代攤提，避免重複扣除。'),
('The cash view replaces equipment allocation with the full purchase, avoiding double counting.','Independent and group purchases of student kits are excluded from this model. For instructor equipment, the cash view replaces allocation with the full purchase, avoiding double counting.'),
('<td>−$32</td><td>−$192</td>','<td>−$12</td><td>−$72</td>'),
('<td>$4</td><td>$24</td>','<td>$24</td><td>$144</td>'),
('<td>$40</td><td>$240</td>','<td>$60</td><td>$360</td>'),
('<td>$76</td><td>$456</td>','<td>$96</td><td>$576</td>'),
('設備投入與現金','學生教材與團購'),('Equipment & cash needs','Student kits & group orders'),
('10 人只需 5 套操作＋至少 1 套備用；先確認現有教具，再比較單套、借用或整組採購。設備成本不能在第一梯的營收中忽略。','每位學生自行購買一套，或湊滿 10 位有購買需求的同學協調團購；平均每套約 US$100，另計適用稅運費。教材歸學生所有，不由課程學費支付。實際供貨、收款與分配方式須在下單前確認。'),
('Ten learners need five active kits plus at least one spare. Check existing inventory before comparing individual kits, loans and a bundle. Initial equipment cash must be budgeted.','Each learner purchases one kit independently, or ten classmates needing kits can coordinate a ten-pack order: approximately US$100 per kit before applicable tax and shipping. Kits belong to students and are not paid from tuition. Confirm availability, payment and distribution before ordering.'),
('均非承諾售價。試辦後','均不含教材且非承諾售價。試辦後'),
('These are planning totals, not committed prices.','These are tuition-only planning totals, excluding kits, not committed prices.'),
('扣除分潤、師資、耗材、行政與 $720 設備攤提後，營運餘額 $1,440；改按首年整筆 $1,000 設備現金支出計，現金餘額約 $1,160。','扣除分潤、師資、耗材與行政後，營運及現金餘額均為 $2,160（教師設備預算為 $0）。每位學生的教材費另由家庭支付，不列為課程營收，也不扣成課程成本。'),
('the operating balance is $1,440 after staff, supplies, overhead, city share and $720 of equipment allocation. Replacing allocation with a full $1,000 first-year equipment purchase gives about $1,160 in cash balance.','operating and cash balances are both $2,160 after staff, supplies, overhead and city share, with no new instructor equipment budgeted. Families pay for their own kits; those purchases are neither course revenue nor course costs.'),
('需五張雙人工作桌、測試空間與一套備用教具。','需容納十套個人教材的工作桌與測試空間；如需教師示範／備用套組，另行編列。'),
('five paired work areas, testing space and a spare kit.','work areas and testing space for ten individual kits; budget separately for any instructor demonstration or spare kits.')
]
for old,new in replacements:
    assert old in s, old
    s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
